name: Transform Tokens
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      - run: npm install
      - run: npx token-transformer tokens.json tokens/foundation.json foundation
      - run: npx token-transformer tokens.json tokens/logee-sales.json foundation,logee-sales foundation
      - run: npx token-transformer tokens.json tokens/logee-transportation.json foundation,logee-transportation foundation
      - run: node build.js
      - name: Setup Node.js environment
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "build: transform tokens"
      - name: Invoke workflow in another repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Transform Tokens
          repo: fahrulseptiana/theme-logee-sales
          token: ${{ secrets.PAT_TOKEN }}
      - name: Invoke workflow in another repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Transform Tokens
          repo: fahrulseptiana/theme-logee-transportation
          token: ${{ secrets.PAT_TOKEN }}