name: Transform Tokens
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      - run: npm install
      - run: npx token-transformer tokens.json tokens/foundation.json foundation
      - run: npx token-transformer tokens.json tokens/logee-sales.json foundation,logee-sales foundation
      - run: node build.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "build: transform tokens"
      - run: |
      curl -XPOST -u "${{secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/fahrulseptiana/theme-logee-sales/dispatches --data '{"event_type": "token_build"}'
